apiVersion: apps/v1
kind: Deployment
metadata:
  name: download-db-backup
  labels:
    backup: download-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      backup: download-backup 
  template:
    metadata:
      labels:
        backup: download-backup
    spec:
      containers:
      - name: dp-dump-download
        image: aasourav/db-dump-download-helper
        ports:
        - containerPort: 8035

---
apiVersion: v1
kind: Service
metadata:
  name: db-backup
spec:
  selector:
    backup: download-backup
  ports:
    - protocol: TCP
      port: 8035
      targetPort: 8035
